version: '3.4'
services:
  web:
    image: mana-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/logs/error.log
    ports:
      - "80:80"
      - "443:443"
    links:
      - app
  app:
    image: mana-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
